---

- name: Assert sansible_ssmtp_group and sansible_ssmtp_user Are Used Together
  assert:
    that:
      - sansible_ssmtp_group is not none
      - sansible_ssmtp_user is not none
  when: sansible_ssmtp_group is not none
          or
        sansible_ssmtp_user is not none

- name: Install SSMTP
  include_tasks: install.yml
  tags:
    - build

- name: Configure SSMTP
  include_tasks: configure.yml
  tags:
    - configure
